### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by sklayn** [oceanhackweek/ohw22-proj-xyzt#12]
- [x] buffering bounding box
- [ ] iterating through dates
- [ ] pass points/bounding box to the copernicus package
- [ ] add depth dimension
- [x] as_BBOX return bbox not polygon
- [ ] add OISST to the ghrsst package

**Comment by btupper** [comment]
BBOX buffering done!

```
> xyzt::read_sab() |> xyzt::as_BBOX()
Geometry set for 1 feature                                                                               
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: -80.185 ymin: 28.508 xmax: -72.248 ymax: 34.714
Geodetic CRS:  WGS 84
POLYGON ((-80.185 28.508, -72.248 28.508, -72.2...
> xyzt::read_sab() |> xyzt::as_BBOX(buffer = c(1,2))
Geometry set for 1 feature                                                                               
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: -81.185 ymin: 26.508 xmax: -71.248 ymax: 36.714
Geodetic CRS:  WGS 84
POLYGON ((-81.185 26.508, -71.248 26.508, -71.2...
```

**Comment by btupper** [comment]
as_BBOX now provides argument to let user request either POLYGON (the default) or BBOX.  Note that all other attributes are now dropped (where we used to retain the first row of attributes, now retain none.)  See https://github.com/BigelowLab/xyzt/commit/478c8c1a435920c77053245c797f70387ce87fb5
